import { Geist, Geist_Mono } from "next/font/google";
import { Bounce, ToastContainer } from "react-toastify";
import Navbar from "./components/navbar/navbar";
import { CartProvider } from "./context/cart/cartContext";
import { UserProvider } from "./context/user/userContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "E-Shelf",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <CartProvider>
            <Navbar>
              <div className="absolute z-0 top-16 w-full">{children}</div>
              <ToastContainer
                position="top-center"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick={false}
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="colored"
                transition={Bounce}
              />
            </Navbar>
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
