import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/navbar/navbar";
import { CartProvider } from "./context/cart/cartContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <Navbar>
            <div className="absolute z-0 top-16">{children}</div>
          </Navbar>
        </CartProvider>
      </body>
    </html>
  );
}
